project:
  type: website
  output-dir: docs

website:
  title: "CursoR-AEET-2022"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Rstats-courses/CursoR-AEET-2022
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Inicio
      - href: preparativos.qmd
        text: Preparativos
      - href: programa.qmd
        text: Programa
      - href: materiales.qmd
        text: Materiales
      - href: proyectos.qmd
        text: Proyectos
      - href: https://github.com/Rstats-courses/CursoR-AEET-2022/discussions
        text: Foro
      - href: https://forms.gle/NeY8tghRtLqjU14CA
        text: Feedback


format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

