---
title: "Programa"
---

Lunes 19 - Viernes 23 Septiembre 

Mañanas: 9:00 - 13:30

Tardes: 15:00 - 17:30

|     |                Mañana               |         Tarde                          |
|:---:|:-----------------------------------:|:--------------------------------------:|
|  L  | Intro + Data manipulation (`dplyr`) | git / GitHub + Students work           |
|  M  | Generalised Linear Models           | Data visualisation (`ggplot2`)         |
|  X  | Mixed models / GAM / Bayes          | Functional programming + Students work |
|  J  | Multivariate analyses               | Reproducible workflows (`Rmarkdown`)     |
|  V  | Using R as GIS + Students work      | Project presentations                  |


## Materiales


### LUNES

#### Mañana

- Introduction [slides](slides/intro.pdf)

- Common-sense stats [slides]()

- Data management [slides]()

#### Tarde

- Git & GitHub [slides]()



### MARTES

#### Mañana

- GLM [slides]()

#### Tarde

- Data visualisation [slides]()


### MIÉRCOLES

#### Mañana

- GLMM [slides]()

#### Tarde

- Functional programming [slides]()


### JUEVES

#### Mañana

- Multivariate analyses [slides]()

#### Tarde

- Reproducible workflows [slides]()


### VIERNES

#### Mañana

- R as GIS [slides]()

#### Tarde





